### ISSUE TITLE
Testing Guidelines for #1 #2 #3 #4 #5 #6

### ISSUE THREAD

**Issue by eag603** [isovera/Tufts-Friedman#12]
Please compile testing guidelines for all six tickets in issue title here for the client.

**Comment by eag603** [comment]
Still wrapping up #6 before starting this.

**Comment by ericmaster** [comment]
Compiling notes in https://docs.google.com/document/d/1tj76r5AV0VF5a6B0lN34dc5BRfNdAa66_EP-vx5fc7I/edit
