### ISSUE TITLE
Related to #17: advising tab on faculty resource page still not opening up

### ISSUE THREAD

**Issue by eag603** [isovera/Tufts-Friedman#19]
It looks like the Advising Resource tab on the Faculty Resource page is still not opening up, but the accordion on the micro-course page is working.

**Comment by ericmaster** [comment]
This is fixed in prod by manually adding missing attributes in hardcoded markup in prod https://nutrition.tufts.edu/faculty/faculty-resources

**Comment by eag603** [comment]
with client for review

**Comment by eag603** [comment]
Xia said: Yes, the accordion looks good
