### ISSUE TITLE
Install/Update Drush for NIL site and test db sync

### ISSUE THREAD

**Issue by ericmaster** [isovera/Tufts-Friedman#8]
Require or update drush to the latest version through composer.

- [x] Update/require drush through composer
- [x] Deploy and verify in dev
- [ ] Merge code to stage and verify database sync to be fixed

**Context:**

This is a short term approach for the issue rised as part of #7 in order to resolve deployment issues.

**LOE:**
2 hours

**Comment by ericmaster** [comment]
**Context:**

This is a short term approach for the issue rised as part of #7 in order to resolve deployment issues.

**Comment by ericmaster** [comment]
**Notes:**

- Refactored drupal installation to a fully composer based installation. Updated modules in the process and reviewed the release notes. Mostly seemed to be updates in prep for Drupal 9 which just removes deprecated functions no longer used.
- Required latest drush package through composer
- Imported live database into local environment, rebuilt caches so that new classes register and executed database updates.
- Moved the webroot to the /web folder instead of being at the same level of the repository root.
- Moved the config folder outside files folder and web root and exported configuration.
- Installed libraries properly through composer
- Working locally, at this point we will need further assistance from Marv most likely so sent e-mail requesting that

**Comment by ericmaster** [comment]
**Notes:**

- This has been deployed to dev and stage. After updating the docroot in dev in the deployment process, rebuilding caches and executing database update refreshed the environment and started to work back again.
- Seems stage needs same tweaking as in dev.

**Comment by eag603** [comment]
- good idea for site owner to freeze content/code in order to deploy to prod. Will need to coordinate to minimize downtime. - Annie and Xia to coordinate with the site owners and find the window that works
- will need to ask Marv to tweak prod as well (Eric to follow up once he confirms stage works after tweaks)

**Comment by ericmaster** [comment]
- After a bit of help from Marv, was able to execute database updates and rebuild caches. The site is loading now.
- Noticed the public files folder was missing in stage and an attempt by Drupal to automatically create it was not possible due to permissions. However, triggering a sync from dev to stage seemed to have fixed that.
- I did not see any errors in the process so content syncing should be fixed now.

For reference the sync output:
https://jenkins.it.tufts.edu/job/drupalpanel-sync-content/3916/console

**Comment by eag603** [comment]
With client for testing: https://tuftsnutrition.zendesk.com/agent/tickets/381

**Comment by eag603** [comment]
Goal was to deploy on Thursday 10/22. Eric and Marv discovered an issue and are working on this together so the deploy will need to be rescheduled.

**Comment by eag603** [comment]
@ericmaster to send Annie/Xia/Marv a status email today.
