### ISSUE TITLE
https://fic.tufts.edu Carousel Update

### ISSUE THREAD

**Issue by eag603** [isovera/Tufts-Friedman#9]
**Background:**
This site: https://fic.tufts.edu/ currently has a carousel on the homepage that feeds in the latest publication attached to each of the 7 research areas on the site. The site owner would like this carousel to feed in the 5 most recent publications regardless of the research theme they are in.

The research themes used to be a major organizing factor on the site, but they are being phased out and decommissioned to some extent on the site. There are some downstream effects from this major change and the homepage carousel feed is one of them.

Annotated screenshot of the publication post type is attached indicating which fields need to pull into the carousel (and which are currently being pulled in).

Annotated screenshot of the homepage carousel is attached indicating all of the fields that need to display and the desired functionality.

Please work with Xia on this request before tackling it. She has been making other site changes and I want to make sure everyone is aligned. Should we all meet soon (the developers, that is) to discuss?

[https://app.zenhub.com/files/233921155/690508e6-63c1-4346-bff8-04df59101fd5/download](https://app.zenhub.com/files/233921155/690508e6-63c1-4346-bff8-04df59101fd5/download)[https://app.zenhub.com/files/233921155/08262a01-3354-4852-81c4-697e2b0d124c/download](https://app.zenhub.com/files/233921155/08262a01-3354-4852-81c4-697e2b0d124c/download)

**Tasks**

- [x] Review requirements and add estimate (including the dev tasks + number of hours to develop and QA) and any questions you have for the client in this ticket

- [x] Conduct call with client to align on work and define process for completing

**Comment by ericmaster** [comment]
**Notes:**

- Checked out the code locally and reviewed the code. Looks the carousel is hardcoded in the template, not the best practice but should be easy to update the query parameters to retrieve the 5 most recent publications.
- Some fields mentioned are already being pulled and may need just minimal change or no change.
- Research area related fields will need to be removed from the template.

This should probably be straightforward to update but given the site is in WP and my WP knowledge is limited and that I don't have experience working with this site yet I would estimate an overall of 4 hours.

**Comment by eag603** [comment]
This is done locally. Eric to deploy this to dev/stage today.

All deployment issues for #8, #9 will be troubleshot today. Eric is having timeout issues connecting to VPN.

**Comment by ericmaster** [comment]
**Notes:**

- Made the requested changes to the corresponding wp template
- Deployed to dev https://fic-dev.tufts.edu and stage https://fic-stage.tufts.edu

**Comment by eag603** [comment]
- summary fields need to be included
- client to review
- no need to coordinate with anyone to deploy to prod.

**Comment by ericmaster** [comment]
Excerpt content display was fixed (restored) and deployed to  dev https://fic-dev.tufts.edu and stage https://fic-stage.tufts.edu.

**Comment by eag603** [comment]
Slacked client to review because I couldn't find the original zendesk ticket.

**Comment by eag603** [comment]
Client approved this and is deploying to prod.
